services:
  fcg_paymentapi:
    build:
      context: .
      dockerfile: Dockerfile
    image: fcg_paymentapi:v2
    ports:
      - "8083:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=PCGPROJ;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True
    networks:
      - pcg-network
    restart: unless-stopped

networks:
  pcg-network:
    external: true
